[package]
name = "basedboard"
version = "0.1.0"
edition = "2021"


[dependencies]
rocket = "0.4.10"
rocket_contrib = {version = "0.4.10", features = ["tera_templates"]}

tera = "1"
colored = {git = "https://github.com/mackwic/colored"}

include_dir = "0.7.2"